### ISSUE TITLE
Sourcemap is likely to be incorrect warning

### ISSUE THREAD

**Issue by Soviut** [zheeeng/vite-plugin-plain-text#1]
I enabled source maps in my Vite build config.

```typescript
export default defineConfig({
  plugins: [
    plainText(/\,hbs$/),
  ],
  
  build: {
    sourcemap: true,
  },
})
```

When I do a build, I get the following error

> Sourcemap is likely to be incorrect: a plugin (plain text) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help

**Comment by zheeeng** [comment]
Update 1.2.0 adding support for sourcemap
