### ISSUE TITLE
Package exports { default }

### ISSUE THREAD

**Issue by ninofiliu** [zheeeng/vite-plugin-plain-text#3]
The type defs and the docs asks to do this in `vite.config.ts`:

```ts
import { defineConfig } from "vite";
import plainText from "vite-plugin-plain-text";

export default defineConfig({
  plugins: [
    plainText(/\.glsl$/),
  ],
});
```

but this is what works for me:

```ts
import { defineConfig } from "vite";
import plainText from "vite-plugin-plain-text";

export default defineConfig({
  plugins: [
    // @ts-ignore
    plainText.default(/\.glsl$/), // <--
  ],
});
```

There seems to be a minor issue in your transpilation/commonjs/build pipeline :)

**Comment by zheeeng** [comment]
Could you provide a minimal reproduction repo? It works fine with my case.

**Comment by ninofiliu** [comment]
https://github.com/ninofiliu/vite-plugin-plain-text-bug

```sh
pnpm run dev
```

expected behavior: launches vite + vite-plugin-plain-text

actual behavior: this output

```txt
> vite-plugin-plain-text-bug@0.0.0 dev /home/nino/c/vite-plugin-plain-text-bug
> vite

failed to load config from /home/nino/c/vite-plugin-plain-text-bug/vite.config.ts
error when starting dev server:
TypeError: plainText is not a function
    at file:///home/nino/c/vite-plugin-plain-text-bug/vite.config.ts.timestamp-1674556087799.mjs:5:13
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
 ELIFECYCLE  Command failed with exit code 1.
```

if that helps:

```console
nino@dell~/c/vite-plugin-plain-text-bugmain$ uname -a
Linux dell 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
nino@dell~/c/vite-plugin-plain-text-bugmain$ node -v
v18.13.0
nino@dell~/c/vite-plugin-plain-text-bugmain$ npm -v
8.19.3
nino@dell~/c/vite-plugin-plain-text-bugmain$ pnpm -v
7.25.1
```

**Comment by zheeeng** [comment]
@ninofiliu I found your package.json has the field "type": "module", it specifies that all module importing is treated as ESM.

**Comment by ninofiliu** [comment]
as it should be? I don't really understand

anyway I found a workaround by not using this plugin entirely and natively using [vite's `?raw`](https://vitejs.dev/guide/assets.html#importing-asset-as-string)

**Comment by zheeeng** [comment]
I can declare the CJS exporting and ESM exporting for your issue. But you still have to handle the other CJS-only packages.

**Comment by zheeeng** [comment]
The latest release v1.3.2 supported your usage.

**Comment by ninofiliu** [comment]
It works indeed, awesome!
